server:
  port: 7788

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    driver-class-name: com.mysql.jdbc.Driver
    platform: mysql
    type: com.alibaba.druid.pool.DruidDataSource
    # 下面为连接池的补充设置，应用到上面所有数据源中
    # 初始化大小，最小，最大
    initialSize: 1
    minIdle: 3
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 30000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    redis:
            # Redis数据库索引（默认为0）
            database: 0
            # Redis服务器地址
            host: 127.0.0.1
            password:
            port: 6379
            pool:
                max-idle: 8
                min-idle: 0
                max-active: 10
                max-wait: -1
                timeout: 6000
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true

bookConfig:
  savePath: ${user.home}/projects/book/upload

logging:
  pattern:
    console: "%d - %msg%n"
  level:
    root: INFO
    org:
      springframework:
        web: INFO
        hibernate: ERROR
  file: ${user.home}/projects/book/logs/book.log
